# Autogenerated wrapper script for FFTW_jll for x86_64-apple-darwin-libgfortran4
export libfftw3, libfftw3_mpi, libfftw3f, libfftw3f_mpi

using MPItrampoline_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("FFTW")
JLLWrappers.@declare_library_product(libfftw3, "@rpath/libfftw3.3.dylib")
JLLWrappers.@declare_library_product(libfftw3_mpi, "@rpath/libfftw3_mpi.3.dylib")
JLLWrappers.@declare_library_product(libfftw3f, "@rpath/libfftw3f.3.dylib")
JLLWrappers.@declare_library_product(libfftw3f_mpi, "@rpath/libfftw3f_mpi.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(MPItrampoline_jll, MicrosoftMPI_jll)
    JLLWrappers.@init_library_product(
        libfftw3,
        "lib/libfftw3.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfftw3_mpi,
        "lib/libfftw3_mpi.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfftw3f,
        "lib/libfftw3f.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfftw3f_mpi,
        "lib/libfftw3f_mpi.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
